import type { Config } from "tailwindcss";
import defaultTheme from "tailwindcss/defaultTheme";

// we can add custom tailwind config here
// most of these settings are generated by shadcn/ui
const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        // we can add custom colors here
        // this brand color is the iconic twitter blue
        // to use it, we can do `className="text-brand"` in our components
        // just like we do `className="text-red-500"` for tailwind's red color
        brand: "#1e9bf0",
      },
      fontFamily: {
        // the `--noto-sans` variable is defined in `./src/app/layout.tsx`
        // now if we do `className="font-sans"` in our components, it will use Noto Sans
        sans: ["var(--noto-sans)", ...defaultTheme.fontFamily.sans],
      },
      // these keyframes and animations are from added by shadcn/ui
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};

export default config;
