import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Header from "@/components/Header";
import { Separator } from "@/components/ui/separator";
import { cn } from "@/lib/utils";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "twitter clone",
  description: "Generated by create next app",
  icons: "/favicon.ico",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "mx-auto flex max-w-3xl")}>
        <Header />
        <main className="flex min-h-screen max-w-xl grow">
          <Separator orientation="vertical" />
          {children}
          <Separator orientation="vertical" />
        </main>
      </body>
    </html>
  );
}
